package com.jatoko.util;

import org.w3c.dom.Document;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * SVG 파일이 아웃라인화(텍스트가 path로 변환됨)되었는지 감지하는 유틸리티.
 *
 * 아웃라인 SVG 특징:
 * - <text> 요소가 없음
 * - 모든 글자가 <path> 요소로 변환됨
 * - Batik Graphics2D SVG Generator로 생성된 경우가 많음
 */
public class SvgOutlineDetector {

    private static final String BATIK_GENERATOR_COMMENT = "Generated by the Batik Graphics2D SVG Generator";

    /**
     * SVG 파일이 아웃라인화되었는지 확인
     *
     * @param file SVG 파일
     * @return 아웃라인 SVG이면 true, 편집 가능한 텍스트가 있으면 false
     */
    public static boolean isOutlined(File file) {
        try {
            return isOutlined(file.toPath());
        } catch (Exception e) {
            // 파싱 실패 시 안전하게 false 반환 (번역 시도 허용)
            return false;
        }
    }

    /**
     * SVG 파일이 아웃라인화되었는지 확인
     *
     * @param path SVG 파일 경로
     * @return 아웃라인 SVG이면 true, 편집 가능한 텍스트가 있으면 false
     */
    public static boolean isOutlined(Path path) throws Exception {
        try (InputStream is = Files.newInputStream(path)) {
            return isOutlined(is);
        }
    }

    /**
     * SVG InputStream이 아웃라인화되었는지 확인
     *
     * @param inputStream SVG 입력 스트림
     * @return 아웃라인 SVG이면 true, 편집 가능한 텍스트가 있으면 false
     */
    public static boolean isOutlined(InputStream inputStream) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setNamespaceAware(true);
        // XXE 방지
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", false);
        factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
        factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

        DocumentBuilder builder = factory.newDocumentBuilder();
        Document document = builder.parse(inputStream);

        return isOutlined(document);
    }

    /**
     * SVG Document가 아웃라인화되었는지 확인
     *
     * @param document SVG DOM Document
     * @return 아웃라인 SVG이면 true, 편집 가능한 텍스트가 있으면 false
     */
    public static boolean isOutlined(Document document) {
        // 1. <text> 요소가 있는지 확인
        NodeList textElements = document.getElementsByTagName("text");
        if (textElements.getLength() > 0) {
            return false; // 텍스트 요소가 있으면 편집 가능
        }

        // 2. <foreignObject> 내부에 텍스트가 있는지 확인 (HTML 임베딩)
        NodeList foreignObjects = document.getElementsByTagName("foreignObject");
        if (foreignObjects.getLength() > 0) {
            return false; // foreignObject가 있으면 편집 가능할 수 있음
        }

        // 3. <tspan> 요소 확인 (text 없이 tspan만 있는 경우는 드물지만 확인)
        NodeList tspanElements = document.getElementsByTagName("tspan");
        if (tspanElements.getLength() > 0) {
            return false;
        }

        // 텍스트 관련 요소가 없으면 아웃라인으로 판단
        return true;
    }

    /**
     * Batik Graphics2D SVG Generator로 생성되었는지 확인
     * (추가 정보용 - 아웃라인 여부와 별개로 확인 가능)
     *
     * @param path SVG 파일 경로
     * @return Batik으로 생성되었으면 true
     */
    public static boolean isBatikGenerated(Path path) {
        try {
            String content = Files.readString(path);
            return content.contains(BATIK_GENERATOR_COMMENT);
        } catch (Exception e) {
            return false;
        }
    }
}
